### ISSUE TITLE
Lakes and islands in lakes

### ISSUE THREAD

**Issue by PaulWessel** [fossgis/osmdata#13]
Nice job on these shapefiles!  Given you seem to have a well-oiled process for extracting global features from OSM, may you consider also extracting features such as lakes and islands-in-lakes (and even ponds-in-islands-in-lakes)? The coastline is great but lakes are important features. I apologize if these are no including in one of your shapefiles - I believe they were not last time I checked (a few years ago).

**Comment by joto** [comment]
There is nothing special required to extract lakes etc. from OpenStreetMap data. Islands in lakes are just holes in multipolygons so there is no special processing required if they are mapped correctly. Existing tools such as osm2pgsql do this just fine. A precursor to this web site had generalized water features for lower zoom levels available but it was discontinued due to lack of time to keep the software current and lack of use.

**Comment by PaulWessel** [comment]
Thanks for your answer.  Does this mean your land polygon shapefile  has those holes or do I need to access the OSM data directly?

**Comment by joto** [comment]
No, the land polygons shapefile is only concerned with land vs. ocean. You need to get the rest from OSM data.
