### ISSUE TITLE
Request for historical coastline data from OSM

### ISSUE THREAD

**Issue by NOLE-GS** [fossgis/osmdata#23]
I am currently working on a project related to the analysis of coastal changes in a specific region. For my research, I am interested in obtaining historical coastline data from OpenStreetMap  for the past 10 years.
I came across your [Git Project] and noticed that you have worked with historical OSM data, particularly with coastlines. I am reaching out to kindly request any available historical coastline data that you might have or any guidance on how to extract historical coastline data from OSM.

**Comment by joto** [comment]
This is totally off-topic here...

You can get OSM planet data with the full OSM history, then use the Osmium tool to get a point-in-time extract for each date you want and use `osmcoastline` to extract the coastline data for each of those points in time.

BUT this is probably not want you want. You'll get the history of the data IN OSM, not necessarily in reality. OSM matured a lot over the last 10 years, got much more detailed. So what you'll get is mostly the changes due to improvements in what OSM was mapping, and it will reflect changes in the real world to a much lesser degree. In short: OSM is not the right dataset, you'll have to look somewhere else.
