### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by brey** [fossgis/osmdata#29]
We are using your `osm` data in our workflow. 

Since, reproducibility is our goal, we are wondering how we can make sure the same dataset can be used at any time consistently. 

I understand you are not provide versioning. Is this something that can be considered? Any ideas?

Thanks

**Comment by joto** [comment]
OSM data is versioned, every OSM object has a version number and a timestamp when it was created. If you want to you can use the [osmcoastline](https://osmcode.org/osmcoastline/) program yourself to re-create the same data available here from the exact OSM data you want to. And anyway, if you download the data and keep the downloaded data you can re-use it and can be sure it is the same data.

**Comment by pmav99** [comment]
Hi @joto thank you for the feedback. 

I can see the timestamp:
1. at the download page
2. at the README file contained in the downloaded zip
3. at the Shapefile's metadata (i.e. `DBF_DATE_LAST_UPDATE`)
I can't find any info WRT the version number though. Do you know how it can be retrieved?

**Comment by joto** [comment]
There is no version number in anything provided on osmdata.openstreetmap.de if that's what you are looking for. But the timestamp can act as a version number. But it isn't useful to you anyway, because old versions are not kept around. So what's the point of referring to an old version of something if that can't be retrieved?

The underlying OSM data is available from planet.osm.org. There is no version number on the files, just a timestamp. But all objects in the data are versioned. You really have to learn more about how OSM data is structured to make use of those in a a sensible way. But the files on planet.osm.org are kept around, every week there is a new file and old files usually don't change. So you could just refer to the URL of the planet file there. Anyway, this goes way beyond what this repo here is about and what help I can provide. So I am closing this here now.

**Comment by pmav99** [comment]
No, no, that's very helpful. Thank you @joto
