### ISSUE TITLE
Preprocessed polygons for marine water bodies (seas, bays & straits)

### ISSUE THREAD

**Issue by jeisenbe** [fossgis/osmdata#3]
### Current situation: No marine water body polygons available

- Many mappers and users on the Tagging mailing list and on the Openstreetmap-Carto issue tracker have said that it would be useful to have polygons available for seas and other marginal marine water bodies such as bays, gulfs, bights, and straits. These features are usually mapped as place=sea, natural=bay and natural=straight as nodes.

- The lack of such polygons has encouraged some mappers to begin creating giant multipolygons for bays, straights and even seas. Other have attempted to map a simplified version of the coastline as an approximation of the extent of the marine body. However, both of these options are difficult to verify, and the large multipolygons are also very difficult to maintain. 

### Recommended solution

- If preprocessed polygons are available for seas, bays (and possibly straits and estuaries), it would be possible to automatically place labels for marine water bodies on maps that do not include the center of the sea, and to adjust the labels size, shape and position based on the polygon, at the time of map rendering.

- It would also be possible to calculate the approximate size of each marine water body for other applications, and to create more specific prompts for marine routing applications.

- Ideally, simplified polygons would be available to match the `simplified-water-polygons` shapefiles, and complete polygons could also be offered which would match the `water-polygons-complete` shapefiles

**Comment by joto** [comment]
This is not the place to talk about (controversial) tagging issues. If and when there is a useful and canonical way of tagging these things and once somebody has written (at least experimental) tools to extract this data, we can talk here about integrating it in this process. Until then I suggest you discuss this on the usual OSM channels.

**Comment by imagico** [comment]
For clarification - i suggested that this kind of processing could be suitable for this project in https://github.com/gravitystorm/openstreetmap-carto/issues/2278#issuecomment-473656155.  But i was a bit ambiguous in my formulation.  It should be clear that a working process would be a prerequisite for discussing it here.

Anyone with experience in OSM-Carto development would probably be able to work on this - you create a separate PostGIS database, import the coastline data and the sea/ocean/etc. stuff and start processing.  You would need to learn new PostGIS stuff (like INSERT and UPDATE in addition to SELECT for example) but can also use a lot of things you already know from style development.

But note - since the issue title suggests otherwise - for labeling maritime features like bays, straits etc. polygon geometries for those are neither necessary nor particularly useful.  Generating a consistent and meaningful set of polygon geometries would be much harder than generating suitable labeling hints.
